accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/guest/', views.guest_register_view, name='guest'),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register_page, name="register"),
]

address/urls.py
from django.urls import path
from . import views

app_name = 'address'

urlpatterns = [
    path('', views.checkout_address_create_view, name='index')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', views.checkout, name='checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.homepage, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('products.urls')),
    path('upload/', include('upload.urls')),
    path('category/', include('category.urls')),
    path('orders/', include('orders.urls')),
    path('billing/', include('billing.urls')),
    path('address/', include('address.urls')),
    path('search/', include('search.urls')),
    path('tags/', include('tags.urls')),
    path('cart/', include('cart.urls')),
    path('tinymce', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='shop'),
    path('<slug>/<int:pk>/detail/', views.ProductDetailView.as_view(), name='detail'),
]

cart/models.py
from django.db import models
from decimal import Decimal
from django.shortcuts import render, redirect
from products.models import Product
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.db.models.signals import m2m_changed



User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
            
        return cart_obj, new_obj
        
        
    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='client', blank=True, null=True)
    products = models.ManyToManyField(Product, verbose_name='Articles', blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2, verbose_name='Prix Hors Taxe')
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2, verbose_name="Prix total TTC ")
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Date de création')
    update = models.DateTimeField(auto_now=True, verbose_name='Mis à jour')
    
    objects = CartManager()
    
    class Meta:
        verbose_name = 'Panier'
        verbose_name_plural = 'Paniers'
        
    
    def __str__(self):
        return f" {self.id} " if self.id else self.email
    
    
    
def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    print(f"Action effectuée : {action}")

    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        print(f"Tous les articles du panier {instance.products.all()}")
        print(f"Prix total avant : {instance.total}")
        products = instance.products.all()
        total = 0
        quantity = 0
        for x in products:
            total += x.price 
            
            # I want to compute quantity and price together but, I got some trouble. Please check me this code.
            # total += Decimal(x.price) * Decimal(x.quantity)
        

        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
                

            
    

def pre_save_cart_receiver(sender, instance, *args, **kwargs):    
    if instance.subtotal > 0:
        # CALCUL DU PRIX TTC : TTC = HT + (1+ TVA%) EN GUINEE LA TVA EST DE 18% DONC 1+18% FERA 1.18
        instance.total = Decimal(instance.subtotal) * Decimal(1.18)
    else:
        instance.total = 0.00
    
    
    
pre_save.connect(pre_save_cart_receiver, sender=Cart)
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

cart/views.py
from importlib.metadata import requires
from django.shortcuts import render, redirect
from django.http import (
    HttpResponse, 
    HttpResponseRedirect,
    Http404, 
    JsonResponse )
from .models import Cart
from accounts.forms import LoginForm, GuestForm
from products.models import Product
from billing.models import BillingProfile
from orders.models import Order
from accounts.models import *
from address.models import Address
from address.forms import AddressForm



def cart_create(user=None):
    cart_obj = Cart.objects.create(user=None)
    return cart_obj
    

def cart(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    template_name = 'cart/cart.html'
    context = {
        'cart': cart_obj,
    }
    return render(request, template_name, context)


def cart_update(request):

    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect('cart:index')

        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)            
        else:
            cart_obj.products.add(product_obj)

        request.session['cart_items'] = cart_obj.products.count() 

        print("-----nombre d'article dans le panier----------")
        print(request.session['cart_items'])
    return redirect('cart:index')


def checkout(request):
    order_obj = None
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    if cart_created or cart_obj.products.count() == 0:
        return redirect('cart:index')

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_form = AddressForm()
    billing_address_id = request.session.get('billing_address_id', None)
    shipping_address_id = request.session.get('shipping_address_id', None)

    # GESTIONNAIRE DU PROFIL D'UTILISATEUR DU SITE
    billing_profile, billing_guest_profile_created = BillingProfile.objects.new_or_get(request)
    
    if billing_profile is not None:
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address =Address.objects.get(id=billing_address_id) 
            del request.session['billing_address_id']
        if shipping_address_id or billing_address_id:
            order_obj.save()
            
    if request.method == "POST":
        #del request.session['cart_id']
        return redirect("/cart/success")
        
    template_name = 'cart/checkout.html'
    context = {
        'object': order_obj,
        'billing_profile': billing_profile,
        'login_form': login_form,
        'guest_form': guest_form,
        'address_form': address_form,
        'billing_address_form': billing_address_form,
    }
    
    return render(request, template_name, context)

templates/cart/cart.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1 style="text-align: center;">Panier ({{ request.session.cart_items }} ) </h1>
        <h2>
            <small> 
                <a href="{% url 'index' %}">Accueil</a>
            </small>
        </h2>
        <h3>
            <a href="{% url 'products:shop' %}">Boutique</a>   
        </h3>

        
        {% if cart.products.exists %}
            <table>
                <thead>
                    <tr>
                        <td>Article</td>
                        <td>Prix</td>
                        <td>Total</td>
                    </tr>
                </thead>
            </table>
            
            {% for product in cart.products.all %}
                {{ forloop.counter }}
                {% include '../cart/update-cart.html' with product=product cart=cart in_cart=True %}
                <br>
                &nbsp;
                <strong> <a href="{{ product.get_absolute_url }}">{{ product.title }}  </a> </strong>
                <p> {{ product.price|floatformat:2 }} GNF </p>
                <img src="{{ product.image.all.first.image.url }}" alt="">
                <br>
                <br>
            {% endfor %}

            <p>Sous total : {{ cart.subtotal }} </p>
            <br>
            <p><strong>Total : {{ cart.total|floatformat:2 }} GNF </strong></p>

            <p>
                <a href="{% url 'cart:checkout' %}">Commander</a>
            </p>
                
        {% else %}
            <p style="text-align: center;">Votre panier est vide</p>
            <a href="{% url 'index' %}">Accueil</a>
        {% endif %}


        <script src="" async defer></script>
    </body>
</html>

templates/cart/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commander</title>
</head>
<body>
    {{ object.order_id }} --- {{ object.cart }}
    
    {% if not billing_profile %}
        <p>
            <a href="{% url 'accounts:login' %}">Se connecter</a>
            {% include 'accounts/snippet/form.html' with form=login_form next_url=request.build_absolute_uri %}
        </p>
        <br>
        <p>Continuer en tant qu'invité ?</p>

        {% url 'accounts:guest' as guest_register_url %}
        {% include 'accounts/snippet/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    
    {% else %}
    
        {% if not object.shipping_address %}
            <h1>Adresse de livraison</h1>
            {% url 'accounts:guest' as checkout_address_create %}
            {% url 'address:index' as address_checkout_url %}
            {% include 'address/form.html' with form=address_form next_url=request.build_absolute_uri action_url=address_checkout_url address_type='shipping' %}
            <br>
            <hr>
        {% elif not object.billing_address %}
            <h1>Adresse de facturation</h1>
            {% url 'accounts:guest' as checkout_address_create %}
            {% url 'address:index' as address_checkout_url %}
            {% include 'address/form.html' with form=address_form next_url=request.build_absolute_uri action_url=address_checkout_url address_type='billing' %}
        {% else %}
            <div style="margin: 20px auto;">
                <h1>Terminé votre paiement</h1>
                <br>
            
                <p>
                    Panier <strong> {{ object.cart.total }} </strong>
                </p>
            
                <p>
                    Frais de livraison <strong> {{ object.shipping_total }} </strong>
                </p>
            
                <p>
                    Total  <strong> {{ object.total }} </strong>
                </p>

                <button>Valider</button>
            </div>
        {% endif %}
    {% endif %}
</body>
</html>

templates/cart/update-cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter au panier</title>
</head>
<body>
    <form action="{% url 'cart:update' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="product_id" value="{{ product.id }}">
        
        {% if in_cart %}
        <button type="submit" >Retirer ?</button>
        {% else %}
            
            {% if product in cart.products.all %}
                <p>Article deja dans le panier</p> <button type="submit" >Ajouter encore ?</button>
            {% else %}
                <button type="submit">Ajouter au panier </button>
            {% endif %}
        
        {% endif %}

    </form>
        

</body>
</html>