accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/guest/', views.guest_register_view, name='guest'),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register_page, name="register"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', views.checkout, name='checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.homepage, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('products.urls')),
    path('upload/', include('upload.urls')),
    path('category/', include('category.urls')),
    path('orders/', include('orders.urls')),
    path('billing/', include('billing.urls')),
    path('address/', include('address.urls')),
    path('search/', include('search.urls')),
    path('tags/', include('tags.urls')),
    path('cart/', include('cart.urls')),
    path('tinymce', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='shop'),
    path('<slug>/<int:pk>/detail/', views.ProductDetailView.as_view(), name='detail'),
]

templates/layouts/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {{ object.title }}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>
            {{ object.title }}
        </h1>

        <p>
            {{ object.image.all }}
        </p>

        {% for item in object.image.all %}
        
        <img src="{{ item.image.url }}" alt=" {{ item.name }} ">
                    
        {% endfor %}


        <p>
            {{ cart }}
        </p>

        {% include '../cart/update-cart.html' with product=object cart=cart %}



        
        <script src="" async defer></script>
    </body>
</html>

templates/layouts/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href=" {% static 'css/style.css' %} ">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li> <a href="{% url 'products:shop' %} ">Shop</a> </li>
                    <li> <a href=" {% url 'cart:index' %} ">Panier  {{ request.session.cart_items }}  </a> </li>

                    {% if request.user.is_authenticated %}
                        
                    <li><a href="{% url 'accounts:logout' %}">Quitter</a></li>

                    <li>
                        <small>Connecté en tant que <strong> {{ request.user }} </strong> </small>
                    </li>
                                            
                    {% else %}

                    <li><a href="{% url 'accounts:register' %}">S'incrire</a></li>
                    <li><a href="{% url 'accounts:login' %}">Se connecter</a></li>
                        
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% lorem 3 p random %}
        <img src=" {% static 'img/beach.jpg' %} ">
        <script src="" async defer></script>
    </body>
</html>

templates/layouts/shop.html
{% for article in object_list %}
{% comment %} 
<a href-"{{ article.get_absolute_url }}">
    {{ article.title }}
</a> {% endcomment %}

    <img src=" {{ article.image.all.first.image.url }} " alt="{{ article.title }}">

    <a href=" {{ article.get_absolute_url }} ">
    {{ article.title }}
    
    {% for cat in article.category.all %}        
    <p>
        {{ cat.category_name }}
    </p>
    {% endfor %}


    
</a>



{% endfor %}

<p>
    <a href="{% url 'index' %}">Accueil</a>
</p>